.TH LEOShell "1" "Febrero 2015" "UTN FRCU" "Manual de usuario"

.SH NOMBRE 
LEOShell - Intérprete de comandos experimental

.SH INTRODUCCIÓN
.PP
LEOShell es un interpréte de comandos experimental desarrollado en Pascal para la cátedra Sistemas Operativos de la Universidad Tecnológica Nacional, Facultad Regional Concepción del Uruguay.
.PP
Su código fuente es libre y se encuentra publicado bajo la Licencia Pública General de GNU (GPL de GNU). El mismo puede descargarse desde su repositorio en GitHub:
.IP 	https://github.com/valeco/LEOShell

.SH COMANDOS Y FUNCIONALIDADES

.SS Comandos internos
.TP
\fBcd\fR [\fIdirectorio\fR]
Cambia el directorio actual de trabajo a \fIdirectorio\fR. Si ningún directorio es especificado, cambia al directorio home del usuario actual.

.TP
\fBpwd\fR
Muestra el directorio actual de trabajo.

.TP
\fBcat\fR [\fIarchivo1\fR] [\fIarchivo2\fR]
Concatena dos archivos y los muestra en la salida estándar. Si se especifica sólo un archivo, lo concatena con la salida estándar.

.TP
\fBls\fR [\fB-a\fR|\fB-f\fR|\fB-l\fR] [\fIdirectorio\fR]
Lista los archivos y directorios de \fIdirectorio\fR. Si no se especifica directorio, listará los del directorio actual de trabajo. A continuación, se detallan las opciones:
.IP
\fB-a\fR Incluye archivos ocultos, con color y ordenados.
.IP
\fB-f\fR Incluye archivos ocultos, sin color y desordenados.
.IP
\fB-l\fR Con color, detalles y ordenados.

.TP
\fBkill\fR [\fIseñal\fR] \fIpid\fR
Envía una \fIseñal\fR a un proceso identificado por \fIpid\fR. Si sólo se especifica un PID, se le envía la señal de terminación (SIGTERM).

.TP
\fBbg\fR [\fIpid\fR]
Continúa en segundo plano la ejecución de un proceso detenido identificado por \fIpid\fR. Si no se especifica un PID, la señal es enviada al último proceso que ha sido detenido. 

.TP
\fBfg\fR [\fIpid\fR]
Continúa en primer plano la ejecución de un proceso detenido identificado por \fIpid\fR. Si no se especifica un PID, la señal es enviada al último proceso que ha sido detenido.

.TP
\fBjobs\fR
Muestra la lista de procesos en segundo plano, junto con su PID, comando asociado y estado actual.

.SS Ejecución en segundo plano
.TP
\fIcomando\fR \fB&\fR
Ejecuta \fIcomando\fR directamente en segundo plano.

.SS Tuberías
.TP
\fIcomando1\fR \fB|\fR \fIcomando2\fR
Conecta dos procesos mediante una tubería de manera tal que, la salida del \fIcomando1\fR es la entrada del \fIcomando2\fR.

.SS Redirección
.TP
\fIcomando\fR \fB>\fR \fIarchivo\fR
La salida de \fIcomando\fR es escrita en \fIarchivo\fR, sobreescribiendo el mismo. Si no existe el archivo, lo crea.

.TP
\fIcomando\fR \fB>>\fR \fIarchivo\fR
La salida de comando es escrita en archivo, concatenando el mismo. Si no existe el archivo, lo crea.

.SH BUGS
.PP
El uso de la unit \fBCRT\fR hace que los comandos externos se muestren de forma errónea en la salida estándar.
.PP
El comando \fBls\fR colorea incorrectamente los nombres de los archivos si un directorio es pasado como argumento.

.SH AUTORES
.PP
+ Costa, Valentín <yafueva@gmail.com>
.br
+ Lonardi, Leandro <leandrolonardi@gmail.com>